// @vitest-environment node
/* eslint-disable @typescript-eslint/no-explicit-any */
import { readFileSync } from 'node:fs'
import { PGlite } from '@electric-sql/pglite'
import { beforeAll,afterAll,describe,it,expect } from 'vitest'
import { lifecycleProposal, lifecycleContext } from '../../supabase/functions/_shared/lifecycle'
const read=(name:string)=>readFileSync(`supabase/migrations/${name}.sql`,'utf8')
const base=read('20260826233501_36b91b63-9c99-426a-9ad4-fd55280d9c6b')
let db:PGlite
const query=async(sql:string,args:any[]=[])=> (await db.query<any>(sql,args)).rows
const rpc=async(name:string,args:any[]=[])=> (await query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args))[0].result
beforeAll(async()=>{
 db=new PGlite()
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create function auth.uid() returns uuid language sql as 'select null::uuid';create schema vault;create table vault.decrypted_secrets(name text,decrypted_secret text);create table tickets(id uuid primary key);create table user_roles(user_id uuid,role text);create function is_admin_or_staff() returns boolean language sql as 'select true';create sequence quote_number_seq;
 create table materials(id uuid primary key default gen_random_uuid(),name text,price_per_yard numeric,full_load_price numeric,full_load_yards numeric,is_active boolean default true,sort_order integer,updated_at timestamptz default now());
 create table app_settings(id integer,company_address text,company_city_state_zip text,delivery_tier_1_max_miles numeric,delivery_tier_1_fee numeric,delivery_tier_2_max_miles numeric,delivery_tier_2_fee numeric,delivery_tier_3_max_miles numeric,delivery_tier_3_fee numeric,delivery_overage_base_fee numeric,delivery_overage_per_mile numeric,tax_enabled boolean,tax_rate numeric,tax_applies_to_delivery boolean);
 insert into app_settings values(1,'7653 S FM 148','Kaufman TX 75142',2,0,5,60,10,100,100,10,false,0,false);`)
 for(const table of ['customers','leads','quotes','quote_items','jobs','invoices','payments','activity_history','control_center_settings','automation_rules','lead_messages'])await db.exec(base.match(new RegExp(`create table if not exists public\\.${table} \\([\\s\\S]*?\\n\\);`))![0])
 await db.exec(`alter table customers add sms_consent_at timestamptz,add sms_consent_source text,add sms_opted_out_at timestamptz;create table contact_submissions(id uuid primary key,customer_id uuid,lead_id uuid,phone text,project_type text,message text,sms_consent boolean,sms_consent_at timestamptz,submitted_at timestamptz,consent_source text);insert into control_center_settings(id) values(1);`)
 await db.exec(base.match(/insert into public\.automation_rules[\s\S]*?on conflict \(id\) do nothing;/)![0])
 for(const file of ['20260913090000_sent_dm_sms_transport','20260913170000_durable_sms_pipeline','20260913171000_sms_consent_and_inbox','20260913172000_communication_worker','20260914190000_initial_response_and_reschedule_intake','20260915010000_ai_material_and_route_intelligence'])await db.exec(read(file))
 await db.exec(`create table ai_audit_logs(id uuid primary key default gen_random_uuid(),created_at timestamptz default now(),status text);`)
 for(const file of ['20260915120000_ai_control_audit','20260915193000_followup_completion','20260915201500_outbound_receipt_reconciliation','20260915220000_ai_lifecycle_actions','20260916120000_approved_change_confirmations','20260916153000_sms_lifecycle_hardening','20260916154000_transactional_quote_recipient','20260916180000_customer_email_and_lead_need'])await db.exec(read(file))
 await db.exec(`create function auth.jwt() returns jsonb language sql as 'select ''{}''::jsonb';create function public.next_quote_number() returns text language sql as 'select ''Q''||nextval(''quote_number_seq'')';alter table ai_audit_logs add lead_id uuid,add decision jsonb,add tool_results jsonb;`)
 await db.exec(read('20260914231500_fix_create_quote_draft_ambiguous_id'))
 await db.exec(read('20260917160000_quote_preparation_and_recipient'))
 await db.exec(read('20260917160000_quote_preparation_and_recipient')) // safe if deployment retries
 // Match the real pre-fix schema, then apply the shipped migration (not a
 // test-only ALTER that could conceal another missing production migration).
 expect(await query("select column_name from information_schema.columns where table_schema='public' and table_name='leads' and column_name='notes'")).toHaveLength(0)
 await db.exec(read('20260918042000_lead_notes_schema'))
 await db.exec(read('20260918042000_lead_notes_schema'))
 await db.exec(read('20260918160000_quote_intake_continuity'))
 await db.exec(read('20260918160000_quote_intake_continuity'))
},30000)
afterAll(async()=>{await db?.close()})
async function fixture(body='my name is Mike'){
 const [c]=await query("insert into customers(name,phone,sms_consent_at,sms_double_opt_in_at) values('Unknown SMS +12145550000','+12145550000',now(),now()) returning *")
 const [l]=await query("insert into leads(customer_id,source,need,conversation_revision) values($1,'Other','Material request',1) returning *",[c.id])
 const [m]=await query("insert into lead_messages(lead_id,customer_id,sender_type,body,delivery_status,message_kind) values($1,$2,'CUSTOMER',$3,'RECEIVED','INBOUND') returning *",[l.id,c.id,body])
 return {c,l,m,apply:(plan:any)=>rpc('apply_ai_lifecycle',[l.id,1,m.id,{write_allowed:true,actions:[],...plan}])}
}
async function transaction(fn:()=>Promise<void>){await db.exec('begin');try{await fn()}finally{await db.exec('rollback')}}
// Dispatch tests need business time regardless of when the suite runs. Select
// a fixed-offset zone at noon inside this rolled-back fixture, not production.
async function businessTimeFixture(){await db.exec("update communication_runtime set timezone=(select name from pg_timezone_names where name like 'Etc/GMT%' and extract(hour from now() at time zone name)=12 limit 1)")}
describe.sequential('executed lifecycle write transactions',()=>{
 it.each(['yes','yes please','sure','please do','send it','yeah'])('retains verified manual prefill after a failed acknowledgement: %s',answer=>transaction(async()=>{
   const a=await fixture('20 yards of flexbase')
   const [material]=await query("insert into materials(name,price_per_yard,full_load_price,full_load_yards) values('Flexbase',38,720,20) returning *")
   await query("update leads set delivery_address='123 Oak Road' where id=$1",[a.l.id])
   await query("insert into ai_audit_logs(lead_id,status,decision,tool_results) values($1,'SUCCESS',$2,$3)",[a.l.id,{dashboard_proposal:{source_message_id:a.m.id}},{pricing:{status:'MATERIAL_CALCULATED',material_id:material.id,yards:20,quantity:{status:'RESOLVED'},route:{status:'ROUTE_CALCULATED',destination:'123 Oak Road',origin:'7653 S FM 148',distance_miles:10}}}])
   await query("insert into lead_messages(lead_id,customer_id,sender_type,body,created_at) values($1,$2,'CUSTOMER',$3,now()+interval '1 second')",[a.l.id,a.c.id,answer])
   await query("insert into ai_audit_logs(lead_id,status) values($1,'FAILED')",[a.l.id])
   const [created]=await query('select * from create_quote_draft_from_lead($1)',[a.l.id])
   const [q]=await query('select * from quotes where id=$1',[created.id])
   expect(Number(q.grand_total)).toBe(820)
   expect((await query('select * from quote_items where quote_id=$1',[q.id]))[0].yards).toBe('20')
   expect((await query('select * from create_quote_draft_from_lead($1)',[a.l.id]))[0].id).toBe(q.id)
 }))
 it('does not reuse audited prices across an unprocessed quantity correction',()=>transaction(async()=>{
   const a=await fixture('20 yards flexbase')
   await query("insert into ai_audit_logs(lead_id,status,decision,tool_results) values($1,'SUCCESS',$2,$3)",[a.l.id,{dashboard_proposal:{source_message_id:a.m.id}},{pricing:{status:'MATERIAL_CALCULATED',quantity:{status:'RESOLVED'},yards:20}}])
   await query("insert into lead_messages(lead_id,customer_id,sender_type,body,created_at) values($1,$2,'CUSTOMER','actually make it 40',now()+interval '1 second')",[a.l.id,a.c.id])
   const [q]=await query('select * from create_quote_draft_from_lead($1)',[a.l.id])
   expect(await query('select * from quote_items where quote_id=$1',[q.id])).toHaveLength(0)
 }))
 it.each([[true,'Use the front gate'],[false,'Use the front gate'],[true,null],[false,null]] as const)('prepares one complete quote through approval, correction and email (profile=%s, notes=%s)',(hasEmail,leadNotes)=>transaction(async()=>{
   const a=await fixture('I need 20 yards of flexbase')
   await query('update customers set name=$2,email=$3 where id=$1',[a.c.id,'Mike',hasEmail?'mike@example.com':null])
   await query('update leads set notes=$2 where id=$1',[a.l.id,leadNotes])
   await query("update customers set notes='Customer profile memo, not quote notes' where id=$1",[a.c.id])
   const [material]=await query("insert into materials(name,price_per_yard,full_load_price,full_load_yards) values('Flexbase',38,720,20) returning *")
   let yards=20
   const pricing=()=>({status:'MATERIAL_CALCULATED',material_id:material.id,material_name:material.name,yards,grand_total:yards*36+Math.ceil(yards/20)*100,quantity:{status:'RESOLVED'},route:{status:'ROUTE_CALCULATED',destination:'123 Oak Road, Kaufman TX',origin:'7653 S FM 148',distance_miles:10}})
   let tick=0
   async function turn(body:string,question?:string) {
     if(question)await query("insert into lead_messages(lead_id,customer_id,sender_type,body,created_at) values($1,$2,'AI',$3,now()+$4*interval '1 second')",[a.l.id,a.c.id,question,++tick])
     const [m]=await query("insert into lead_messages(lead_id,customer_id,sender_type,body,created_at) values($1,$2,'CUSTOMER',$3,now()+$4*interval '1 second') returning *",[a.l.id,a.c.id,body,++tick])
     const [lead]=await query('update leads set conversation_revision=conversation_revision+1 where id=$1 returning *',[a.l.id])
     const [customer]=await query('select * from customers where id=$1',[a.c.id])
     const messages=await query('select * from lead_messages where lead_id=$1 order by created_at,id',[a.l.id])
     const quotes=await query('select * from quotes where lead_id=$1 order by created_at desc',[a.l.id])
     const proposal=lifecycleProposal({lead,customer,messages,lifecycle:lifecycleContext(lead,quotes,[],[],[]),decision:{uncertain_facts:[]},pricing:pricing()})
     const applied=await rpc('apply_ai_lifecycle',[lead.id,lead.conversation_revision,m.id,{...proposal,write_allowed:true}])
     return {proposal,applied}
   }
   await turn('tomorrow')
   expect((await query('select requested_delivery_date from leads where id=$1',[a.l.id]))[0].requested_delivery_date).toBeTruthy()
   await turn('10am','what time works best that day?')
   const approval=await turn('yes','would you like us to prepare the quote?')
   expect(approval.proposal.quote_requested).toBe(true)
   expect(approval.applied.quote_id).toBeTruthy();expect(approval.applied.ready).toBe(false)
   yards=40
   const corrected=await turn('actually make it 40 yards')
   expect(corrected.proposal.quote_requested).toBe(true)
   const final=hasEmail?await turn('yes','i have mike@example.com. is that where you want us to send it?'):await turn('mike@example.com','what email should we send the quote to?')
   expect(final.applied).toMatchObject({ready:true,quote_id:approval.applied.quote_id})
   const [q]=await query('select * from quotes where lead_id=$1',[a.l.id])
   expect(q).toMatchObject({status:'DRAFT',confirmed_email:'mike@example.com',address:'123 Oak Road, Kaufman TX',notes:leadNotes})
   expect(q.requested_delivery_time).toBe('10:00:00');expect(q.ai_ready_at).toBeTruthy()
   expect(Number(q.materials_subtotal)).toBe(1440);expect(Number(q.delivery_total)).toBe(200);expect(Number(q.grand_total)).toBe(1640)
   expect((await query('select sum(yards)::float yards from quote_items where quote_id=$1',[q.id]))[0].yards).toBe(40)
   expect(await query('select * from quotes where lead_id=$1',[a.l.id])).toHaveLength(1)
   expect(await query('select * from sms_outbox')).toHaveLength(0)
   await rpc('confirm_quote_recipient',[q.id,'alternate@example.com'])
   await rpc('confirm_quote_recipient',[q.id,'alternate@example.com'])
   expect((await query('select email from customers where id=$1',[a.c.id]))[0].email).toBe('mike@example.com')
   expect((await query('select confirmed_email from quotes where id=$1',[q.id]))[0].confirmed_email).toBe('alternate@example.com')
   expect(await query("select * from activity_history where entity_id=$1 and event_type='RECIPIENT_CONFIRMED'",[q.id])).toHaveLength(1)
   const [existing]=await query('select * from create_quote_draft_from_lead($1)',[a.l.id]);expect(existing.id).toBe(q.id)
 }))
 it.each(['Use the side gate',null])('manual quote creation reuses verified intake and rejects stale calculations (notes=%s)',leadNotes=>transaction(async()=>{
   const a=await fixture('please prepare the quote')
   const [material]=await query("insert into materials(name,price_per_yard,full_load_price,full_load_yards) values('Flexbase',38,720,20) returning *")
   await query("update leads set delivery_address='123 Oak Road',requested_delivery_date=current_date+1,requested_delivery_time='10:00',quote_confirmed_email='mike@example.com' where id=$1",[a.l.id])
   await query('update leads set notes=$2 where id=$1',[a.l.id,leadNotes])
   await query("update customers set notes='Separate customer note' where id=$1",[a.c.id])
   await query("insert into ai_audit_logs(lead_id,status,decision,tool_results) values($1,'SUCCESS',$2,$3)",[a.l.id,{dashboard_proposal:{source_message_id:a.m.id}},{pricing:{status:'MATERIAL_CALCULATED',material_id:material.id,yards:40,quantity:{status:'RESOLVED'},route:{status:'ROUTE_CALCULATED',destination:'123 Oak Road',origin:'7653 S FM 148',distance_miles:10}}}])
   const [created]=await query('select * from create_quote_draft_from_lead($1)',[a.l.id])
   const [q]=await query('select * from quotes where id=$1',[created.id])
   expect(q.confirmed_email).toBe('mike@example.com');expect(Number(q.grand_total)).toBe(1640)
   expect(q.notes).toBe(leadNotes)
   expect((await query('select notes from customers where id=$1',[a.c.id]))[0].notes).toBe('Separate customer note')
   const b=await fixture('actually a different material')
   await query("insert into ai_audit_logs(lead_id,status,decision,tool_results) values($1,'SUCCESS',$2,$3)",[b.l.id,{dashboard_proposal:{source_message_id:a.m.id}},{pricing:{status:'MATERIAL_CALCULATED',material_id:material.id,yards:40,quantity:{status:'RESOLVED'}}}])
   const [empty]=await query('select * from create_quote_draft_from_lead($1)',[b.l.id])
   expect(await query('select * from quote_items where quote_id=$1',[empty.id])).toHaveLength(0)
 }))
 it('approves the saved modified schedule, reserves once and keeps staff takeover',()=>transaction(async()=>{
   await businessTimeFixture()
   const a=await fixture('can we move it to Friday at 10am?')
   const actor='00000000-0000-0000-0000-000000000001'
   await db.exec(`create or replace function auth.uid() returns uuid language sql as 'select ''${actor}''::uuid';insert into user_roles values('${actor}','admin');update control_center_settings set sms_status='READY',business_number='+19453750877';update communication_runtime set business_start_hour=0,business_end_hour=23,business_days=array[1,2,3,4,5,6,7]`)
   const [q]=await query("insert into quotes(quote_number,customer_id,lead_id,status,grand_total) values('APPROVE',$1,$2,'ACCEPTED',900) returning *",[a.c.id,a.l.id])
   const [j]=await query("insert into jobs(customer_id,quote_id,category,scheduled_date,scheduled_time,address,description,agreed_amount) values($1,$2,'MATERIAL_DELIVERY',current_date+5,'14:00','123 Oak','Delivery',900) returning *",[a.c.id,q.id])
   const id=await rpc('open_ai_staff_action',[a.l.id,a.m.id,'SCHEDULE_CHANGE',{quote_id:q.id,job_id:j.id,requested_time:'10:00'}])
   const saved=await rpc('preview_ai_change_approval',[id]);expect(saved.time).toBe('02:00 PM')
   const result=await rpc('decide_ai_staff_action',[id,'Approved saved time','APPROVED',saved])
   expect(await rpc('decide_ai_staff_action',[id,'Double click','APPROVED',saved])).toEqual(result)
   const outbox=await query('select * from sms_outbox');expect(outbox).toHaveLength(1)
   const [message]=await query('select body from lead_messages where id=$1',[result.message_id]);expect(message.body).toContain('02:00 PM');expect(message.body).not.toContain('10:00')
   expect((await query('select human_takeover from leads where id=$1',[a.l.id]))[0].human_takeover).toBe(true)
   const claim=await rpc('claim_sms',[result.message_id]);expect(await rpc('authorize_sms_dispatch',[result.message_id,claim.lease_token])).toBeTruthy()
 }))
 it.each(['REJECTED','CANCELLED','HANDLED'])('never sends a %s change request',outcome=>transaction(async()=>{
   const a=await fixture();const id=await rpc('open_ai_staff_action',[a.l.id,a.m.id,'ORDER_CHANGE',{}])
   await rpc('decide_ai_staff_action',[id,'Reviewed request',outcome,null]);expect(await query('select * from sms_outbox')).toHaveLength(0)
   await db.exec('savepoint retry');await expect(rpc('decide_ai_staff_action',[id,'Try approval','APPROVED',{}])).rejects.toThrow('already resolved');await db.exec('rollback to savepoint retry')
 }))
 it('rejects stale approval previews and cancels changed approved values before sending',()=>transaction(async()=>{
   await businessTimeFixture()
   const a=await fixture();const actor='00000000-0000-0000-0000-000000000001'
   await db.exec(`create or replace function auth.uid() returns uuid language sql as 'select ''${actor}''::uuid';insert into user_roles values('${actor}','admin');update control_center_settings set sms_status='READY',business_number='+19453750877';update communication_runtime set business_start_hour=0,business_end_hour=23,business_days=array[1,2,3,4,5,6,7]`)
   const [q]=await query("insert into quotes(quote_number,customer_id,lead_id,status,grand_total) values('QUANTITY',$1,$2,'ACCEPTED',900) returning *",[a.c.id,a.l.id])
   await query("insert into quote_items(quote_id,kind,description,yards,line_total) values($1,'MATERIAL','Flexbase',25,900)",[q.id])
   const id=await rpc('open_ai_staff_action',[a.l.id,a.m.id,'ORDER_CHANGE',{quote_id:q.id,request:'5 more yards'}])
   const before=await rpc('preview_ai_change_approval',[id]);await query('update quote_items set yards=30 where quote_id=$1',[q.id])
   await db.exec('savepoint stale');await expect(rpc('decide_ai_staff_action',[id,'Approved','APPROVED',before])).rejects.toThrow('Saved details changed');await db.exec('rollback to savepoint stale')
   const current=await rpc('preview_ai_change_approval',[id]);const result=await rpc('decide_ai_staff_action',[id,'Approved','APPROVED',current])
   expect((await query('select body from lead_messages where id=$1',[result.message_id]))[0].body).toContain('30 yards')
   await query('update quote_items set yards=35 where quote_id=$1',[q.id])
   const claim=await rpc('claim_sms',[result.message_id]);expect(await rpc('authorize_sms_dispatch',[result.message_id,claim.lease_token])).toBeNull()
   expect((await query('select state from sms_outbox'))[0].state).toBe('CANCELLED')
 }))
 it('keeps email acknowledgments behind a successful controlled write',()=>transaction(async()=>{
   const a=await fixture('update my email to treytest@gmail.com')
   expect(await a.apply({email:'treytest@gmail.com'})).toMatchObject({status:'APPLIED'})
   expect((await query('select email from customers where id=$1',[a.c.id]))[0].email).toBe('treytest@gmail.com')
 }))
 it('carries a normal quote-stage email through the customer record to its later invoice',()=>transaction(async()=>{
   const a=await fixture('mike@example.com')
   await a.apply({email:'mike@example.com',confirmed_email:'mike@example.com'})
   const [q]=await query("insert into quotes(quote_number,customer_id,lead_id,status,confirmed_email,grand_total) values('EMAIL-LIFE',$1,$2,'ACCEPTED','mike@example.com',900) returning id",[a.c.id,a.l.id])
   const [j]=await query("insert into jobs(customer_id,quote_id,category,status,scheduled_date,address,description,agreed_amount) values($1,$2,'MATERIAL_DELIVERY','COMPLETED',current_date,'123 Oak','Delivery',900) returning id",[a.c.id,q.id])
   const [invoice]=await query("insert into invoices(invoice_number,customer_id,job_id,quote_id,amount_source,description,amount,status) values('EMAIL-I',$1,$2,$3,'JOB','Delivery',900,'DRAFT') returning id",[a.c.id,j.id,q.id])
   const [recipient]=await query('select c.email from invoices i join customers c on c.id=i.customer_id where i.id=$1',[invoice.id])
   expect(recipient.email).toBe('mike@example.com')
 }))
 it('updates by customer ID, does not merge first names and audits once',()=>transaction(async()=>{
   const a=await fixture(),b=await fixture();await a.apply({name:'Mike'});await b.apply({name:'Mike'});await a.apply({name:'Mike'})
   expect((await query("select count(*)::int n from customers where name='Mike'"))[0].n).toBe(2)
   const audits=await query("select metadata from activity_history where event_type='AI_LIFECYCLE_APPLIED'")
   expect(audits).toHaveLength(2);expect(audits[0].metadata.before.customer.name).toContain('Unknown');expect(audits[0].metadata.after.customer.name).toBe('Mike')
 }))
 it('rejects stale revisions, fabricated names and unauthenticated writes',()=>transaction(async()=>{
   const a=await fixture();await db.exec('savepoint invalid_name');await expect(a.apply({name:'Not In Message'})).rejects.toThrow('current customer');await db.exec('rollback to savepoint invalid_name')
   expect(await rpc('apply_ai_lifecycle',[a.l.id,0,a.m.id,{write_allowed:true,name:'Mike'}])).toMatchObject({status:'STALE'})
   expect((await query("select has_function_privilege('authenticated','public.apply_ai_lifecycle(uuid,bigint,uuid,jsonb)','EXECUTE') allowed"))[0].allowed).toBe(false)
 }))
 it('prepares an untouched quote with real calculation, email and date; never sends',()=>transaction(async()=>{
   const a=await fixture('send the quote to mike@example.com tomorrow at noon')
   const [material]=await query("insert into materials(name,price_per_yard,full_load_price,full_load_yards,is_active) values('Flexbase',38,720,20,true) returning id")
   const date=(await query("select ((now() at time zone 'America/Chicago')::date+1)::text value"))[0].value
   const p={email:'mike@example.com',confirmed_email:'mike@example.com',quote_requested:true,requested_date:date,requested_time:'12:00',requested_text:'tomorrow at noon',ready:true,context:{pricing:{status:'MATERIAL_CALCULATED',material_id:material.id,yards:20,quantity:{status:'RESOLVED'},route:{status:'ROUTE_CALCULATED',destination:'123 Oak Road, Kaufman TX',origin:'7653 S FM 148',distance_miles:10}}}}
   expect(await a.apply(p)).toMatchObject({status:'APPLIED',ready:true})
   const [q]=await query('select * from quotes where lead_id=$1',[a.l.id]);expect(q.status).toBe('DRAFT');expect(Number(q.grand_total)).toBe(820);expect(q.confirmed_email).toBe('mike@example.com');expect(q.ai_ready_at).toBeTruthy()
   expect(await query('select * from open_ai_staff_actions()')).toHaveLength(1)
   await query("update quotes set status='SENT' where id=$1",[q.id]);expect(await query('select * from open_ai_staff_actions()')).toHaveLength(0)
   expect(await query('select * from sms_outbox')).toHaveLength(0)
 }))
 it('does not edit accepted financial terms or calendar, but adds job instructions and requests',()=>transaction(async()=>{
   const a=await fixture('gate code is 5521')
   const [q]=await query("insert into quotes(quote_number,customer_id,lead_id,status,grand_total) values('SAFE', $1,$2,'ACCEPTED',900) returning *",[a.c.id,a.l.id])
   const [j]=await query("insert into jobs(customer_id,quote_id,category,scheduled_date,address,description,agreed_amount) values($1,$2,'MATERIAL_DELIVERY',current_date+2,'123 Oak','Delivery',900) returning *",[a.c.id,q.id])
   await a.apply({job_note:'gate code is 5521',actions:['ORDER_CHANGE','SCHEDULE_CHANGE'],requested_date:new Date().toISOString().slice(0,10),context:{quote_id:q.id,job_id:j.id,request:'change requested'}})
   expect((await query('select grand_total from quotes where id=$1',[q.id]))[0].grand_total).toBe(q.grand_total)
   const [updated]=await query('select * from jobs where id=$1',[j.id]);expect(updated.scheduled_date).toEqual(j.scheduled_date);expect(updated.notes).toContain('5521')
   const actions=await query('select * from open_ai_staff_actions()');expect(actions).toHaveLength(2)
   await rpc('resolve_ai_staff_action',[actions[0].id,'Reviewed with customer']);await rpc('resolve_ai_staff_action',[actions[0].id,'Already handled']);expect(await query('select * from open_ai_staff_actions()')).toHaveLength(1)
 }))
 it('reserves one acknowledgment and pauses atomically while preserving final consent checks',()=>transaction(async()=>{
   const a=await fixture('I want Salvador')
   await db.exec("update control_center_settings set sms_status='READY',business_number='+19453750877';update communication_runtime set ai_sending_enabled=true")
   const [job]=await query("insert into communication_jobs(operation_key,kind,lead_id,trigger_message_id,context,state,lease_token,lease_until) values('ack-test','AI_REPLY',$1,$2,$3,'WORKING',gen_random_uuid(),now()+interval '1 minute') returning *",[a.l.id,a.m.id,{conversation_revision:1}])
   const result=await rpc('finish_ai_handoff',[job.id,job.lease_token,false,null]);expect(result.body).toContain('Salvador');expect((await query('select human_takeover from leads where id=$1',[a.l.id]))[0].human_takeover).toBe(true)
   expect(await rpc('finish_ai_handoff',[job.id,job.lease_token,false,null])).toBeNull();expect(await query('select * from sms_outbox')).toHaveLength(1)
   const claimed=await rpc('claim_sms',[result.id]);expect(await rpc('authorize_sms_dispatch',[result.id,claimed.lease_token])).toBeTruthy()
 }))
 it('does not merge an email collision or partially update the name',()=>transaction(async()=>{
   const a=await fixture('my name is Mike. use shared@example.com'),b=await fixture()
   await query("update customers set email='shared@example.com',normalized_email='shared@example.com' where id=$1",[b.c.id])
   expect(await a.apply({name:'Mike',email:'shared@example.com'})).toMatchObject({status:'CONTACT_REVIEW'})
   expect((await query('select name,email from customers where id=$1',[a.c.id]))[0]).toMatchObject({name:a.c.name,email:null})
   expect(await query('select * from open_ai_staff_actions()')).toHaveLength(1)
 }))
 it('keeps an explicit alternate Quote recipient from overwriting the customer profile',()=>transaction(async()=>{
   const a=await fixture('send this quote to shared@example.com'),b=await fixture()
   await query("update customers set email='profile@example.com',normalized_email='profile@example.com' where id=$1",[a.c.id])
   await query("update customers set email='shared@example.com',normalized_email='shared@example.com' where id=$1",[b.c.id])
   expect(await a.apply({confirmed_email:'shared@example.com'})).toMatchObject({status:'APPLIED'})
   expect((await query('select email from customers where id=$1',[a.c.id]))[0].email).toBe('profile@example.com')
   expect((await query('select quote_confirmed_email from leads where id=$1',[a.l.id]))[0].quote_confirmed_email).toBe('shared@example.com')
   expect(await query("select * from open_ai_staff_actions() where metadata->>'kind'='CONTACT_REVIEW'")).toHaveLength(0)
 }))
 it('classifies an inbound material quantity as delivery from cited customer evidence',()=>transaction(async()=>{
   const a=await fixture('how much for 32 yards of flexbase?')
   expect((await query("select has_function_privilege('authenticated','public.apply_ai_lead_need(uuid,bigint,uuid,text,text)','EXECUTE') allowed"))[0].allowed).toBe(false)
   await db.exec('savepoint invalid_need_evidence')
   await expect(rpc('apply_ai_lead_need',[a.l.id,1,a.m.id,'material-delivery','fabricated request'])).rejects.toThrow('cited customer message')
   await db.exec('rollback to savepoint invalid_need_evidence')
   expect(await rpc('apply_ai_lead_need',[a.l.id,1,a.m.id,'material-delivery',a.m.body])).toMatchObject({status:'APPLIED',need:'material-delivery',changed:true})
   expect((await query('select need from leads where id=$1',[a.l.id]))[0].need).toBe('material-delivery')
   expect(await rpc('apply_ai_lead_need',[a.l.id,1,a.m.id,'material-delivery',a.m.body])).toMatchObject({status:'ALREADY_APPLIED'})
 }))
 it('classifies an explicit pickup request as pickup, never delivery',()=>transaction(async()=>{
   const a=await fixture('I need 20 yards of crushed concrete and I will pick it up')
   await rpc('apply_ai_lead_need',[a.l.id,1,a.m.id,'material-pickup',a.m.body])
   expect((await query('select need from leads where id=$1',[a.l.id]))[0].need).toBe('material-pickup')
 }))
 it('updates the lead need when a later customer message clarifies the project',()=>transaction(async()=>{
   const a=await fixture('how much for 32 yards of flexbase?')
   await rpc('apply_ai_lead_need',[a.l.id,1,a.m.id,'material-delivery',a.m.body])
   const [clarification]=await query("insert into lead_messages(lead_id,customer_id,sender_type,body,delivery_status,message_kind) values($1,$2,'CUSTOMER','I actually need you to regrade my driveway','RECEIVED','INBOUND') returning *",[a.l.id,a.c.id])
   await rpc('apply_ai_lead_need',[a.l.id,1,clarification.id,'driveway',clarification.body])
   expect((await query('select need from leads where id=$1',[a.l.id]))[0].need).toBe('driveway')
   expect(await query("select * from activity_history where entity_id=$1 and event_type='AI_LEAD_NEED_UPDATED'",[a.l.id])).toHaveLength(2)
 }))
 it('reserves one unknown-sender opt-in and resumes the saved inquiry after YES',()=>transaction(async()=>{
   await db.exec("update control_center_settings set sms_status='TESTING',business_number='+19453750877';update communication_runtime set ai_sending_enabled=true,test_numbers=array['+12145550991']")
   const first=await rpc('record_inbound_sms',['unknown-optin-1','+12145550991','I need 10 yards of gravel'])
   expect(first).toMatchObject({needs_opt_in:true})
   const [timing]=await query("select metadata from activity_history where metadata->>'provider_message_id'='unknown-optin-1'")
   expect(Number(timing.metadata.provider_to_record_ms)).toBeGreaterThanOrEqual(0)
   expect(timing.metadata.provider_occurred_at).toBeTruthy()
   expect(timing.metadata.webhook_recorded_at).toBeTruthy()
   const reserved=await rpc('reserve_inbound_opt_in',[first.lead_id,first.message_id,'approved-template'])
   expect((await rpc('reserve_inbound_opt_in',[first.lead_id,first.message_id,'approved-template'])).id).toBe(reserved.id)
   expect((await query('select human_takeover from leads where id=$1',[first.lead_id]))[0].human_takeover).toBe(false)
   const claim=await rpc('claim_sms',[reserved.id]);expect(await rpc('authorize_sms_dispatch',[reserved.id,claim.lease_token])).toBeTruthy()
   await rpc('complete_sms_dispatch',[reserved.id,claim.lease_token,'provider-optin','SENT'])
   const [consent]=await query('select sms_consent_at,sms_opt_in_requested_at,sms_opt_in_request_message_id from customers where id=$1',[first.customer_id])
   expect(consent).toMatchObject({sms_consent_at:expect.any(Date),sms_opt_in_requested_at:expect.any(Date),sms_opt_in_request_message_id:reserved.id})
   const yes=await rpc('record_inbound_sms',['unknown-optin-yes','+12145550991','YES'])
   expect(yes).toMatchObject({consent_confirmed:true,resume_message_id:first.message_id})
   const [job]=await query('select context from communication_jobs where id=$1',[yes.job_id])
   expect(job.context.resume_message_id).toBe(first.message_id)
 }))
 it('captures a payment claim without recording payment or marking paid',()=>transaction(async()=>{
   const a=await fixture('I already paid')
   const [q]=await query("insert into quotes(quote_number,customer_id,lead_id,status,grand_total) values('CLAIM',$1,$2,'ACCEPTED',300) returning id",[a.c.id,a.l.id])
   const [i]=await query("insert into invoices(invoice_number,customer_id,quote_id,amount_source,description,amount,status) values('CLAIM-I',$1,$2,'QUOTE','Material',300,'SENT') returning id",[a.c.id,q.id])
   await a.apply({write_allowed:false,actions:['PAYMENT_CLAIM'],context:{invoice_id:i.id}})
   expect((await query('select status,payment_claimed_at from invoices where id=$1',[i.id]))[0]).toMatchObject({status:'SENT',payment_claimed_at:expect.any(Date)})
   expect(await query('select * from payments')).toHaveLength(0)
   expect(await query('select * from open_ai_staff_actions()')).toHaveLength(1)
   const audit=(await query("select metadata from activity_history where event_type='AI_LIFECYCLE_APPLIED'"))[0].metadata
   expect(audit.before.invoice.payment_claimed_at).toBeNull();expect(audit.after.invoice.payment_claimed_at).toBeTruthy()
   await query("update invoices set status='PAID' where id=$1",[i.id])
   expect(await query('select * from open_ai_staff_actions()')).toHaveLength(0)
 }))
 it('keeps manual draft financial values protected',()=>transaction(async()=>{
   const a=await fixture('send the quote to mike@example.com')
   const [material]=await query("insert into materials(name,price_per_yard,full_load_price,full_load_yards) values('Flexbase',38,720,20) returning id")
   const [q]=await query("insert into quotes(quote_number,customer_id,lead_id,status,grand_total,delivery_distance_source,delivery_fee_per_load) values('MANUAL',$1,$2,'DRAFT',777,'MANUAL',77) returning id",[a.c.id,a.l.id])
   await query("insert into quote_items(quote_id,kind,description,line_total) values($1,'CUSTOM_WORK','Protected scope',700)",[q.id])
   const result=await a.apply({ready:true,context:{pricing:{material_id:material.id,yards:20,quantity:{status:'RESOLVED'},route:{status:'ROUTE_CALCULATED',destination:'New destination',origin:'Yard',distance_miles:20}}}})
   expect(result.ready).toBe(false);expect(Number((await query('select grand_total from quotes where id=$1',[q.id]))[0].grand_total)).toBe(777)
 }))
 it('denies a stale handoff and blocks an acknowledged handoff after STOP',()=>transaction(async()=>{
   const a=await fixture('Salvador please')
   await db.exec("update control_center_settings set sms_status='READY',business_number='+19453750877';update communication_runtime set ai_sending_enabled=true")
   const [job]=await query("insert into communication_jobs(operation_key,kind,lead_id,trigger_message_id,context,state,lease_token,lease_until) values('ack-stop','AI_REPLY',$1,$2,$3,'WORKING',gen_random_uuid(),now()+interval '1 minute') returning *",[a.l.id,a.m.id,{conversation_revision:0}])
   expect(await rpc('finish_ai_handoff',[job.id,job.lease_token,false,null])).toBeNull()
   expect((await query('select human_takeover from leads where id=$1',[a.l.id]))[0].human_takeover).toBe(false)
   await query("update communication_jobs set state='WORKING',context=$2 where id=$1",[job.id,{conversation_revision:1}])
   const result=await rpc('finish_ai_handoff',[job.id,job.lease_token,false,null])
   await query('update customers set sms_opted_out_at=now() where id=$1',[a.c.id])
   const claimed=await rpc('claim_sms',[result.id]);expect(await rpc('authorize_sms_dispatch',[result.id,claimed.lease_token])).toBeNull()
 }))
 it('creates a fresh lead for returning work without a second customer or altered history',()=>transaction(async()=>{
   const a=await fixture('I want another load of gravel')
   const [q]=await query("insert into quotes(quote_number,customer_id,lead_id,status,grand_total) values('HISTORY',$1,$2,'ACCEPTED',900) returning id",[a.c.id,a.l.id])
   await query("insert into jobs(customer_id,quote_id,category,status,scheduled_date,address,description,agreed_amount) values($1,$2,'MATERIAL_DELIVERY','COMPLETED',current_date-60,'Old site','Old delivery',900)",[a.c.id,q.id])
   const result=await a.apply({actions:['NEW_WORK'],context:{request:a.m.body}});expect(result.new_lead_id).toBeTruthy()
   await a.apply({actions:['NEW_WORK']});expect(await query('select * from customers')).toHaveLength(1);expect(await query('select * from leads')).toHaveLength(2)
   expect((await query('select status,grand_total from quotes where id=$1',[q.id]))[0]).toMatchObject({status:'ACCEPTED',grand_total:'900'})
 }))
})
